dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# Latest node
before_install:
  - nvm install 12.6.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.2
  - export PATH=$HOME/.yarn/bin:$PATH
# Install dependencies
install:
  - yarn install
  - yarn build
  - yarn copy
  - cd py
  - pip install -U pip
  - pip install swiglpk --only-binary swiglpk
  - pip install -e .
  - cd ..
# Run tests
script:
  - yarn test
  - if [[ $TRAVIS_PYTHON_VERSION = '3.7' ]]; then yarn coverage; fi
  - cd py
  - python -m pytest
  - cd ..
# No emails
notifications:
  email: false
# Run with containers
sudo: false
